### ISSUE TITLE
"error_reason":"invalid_redirect_uri"

### ISSUE THREAD

**Issue by MPH-DZP** [FusionAuth/fusionauth-example-5-minute-guide#3]
According to https://fusionauth.io/docs/v1/tech/oauth/#exchange-the-authorization-code-for-an-access-token , I would expect that `/oauth-redirect` at

https://github.com/FusionAuth/fusionauth-example-5-minute-guide/blob/22652f49d2c4d2bb62a74947124bc72106c35937/routes/index.js#L55

should instead be `/oauth2/token`. Yet for both after responding to a login form I get an error like:
```
{"statusCode":400,"exception":{"error":"invalid_grant","error_description":"redirect_uri: https://MYAPP.fusionauth.io/oauth2/token is not valid.","error_reason":"invalid_redirect_uri"}}
```

**Comment by MPH-DZP** [comment]
On further consideration, it seems that the url highlighted above should _*not*_ have query path `/oath2/token` because that goes to the FA instance (but how would the `exchangeOAuthCodeForAccessTokenUsingPKCE` fn know where to send it?).

Still, using the query path `/oath-redirect` would seem to cause an infinite cycle of requests to the FA instance for which it would respond back to `/oath-redirect`. It seems some other query path and handler is needed.

**Comment by MPH-DZP** [comment]
I found https://github.com/FusionAuth/fusionauth-typescript-client/blob/5571ccf3cc3691cdf67242d2466053540c6bd1d9/src/FusionAuthClient.ts#L1455 but I still don't understand why a handler for route X would specify X as a redirect_url when the handler has no logic for, say, detecting that query params are different so it could avoid an infinite loop of inter-server requests.

**Comment by mooreds** [comment]
`http://localhost:3000/oauth-redirect` is the local route which catches the authorization code, and then exchanges it for a token from `http://localhost:9011/oauth2/token`

the server running at 9011 is FusionAuth

the server running at 3000 is custom code. 

https://github.com/FusionAuth/fusionauth-example-5-minute-guide/blob/master/routes/index.js#L41 is the custom code, and it uses, on line 52, the FusionAuth client library, but it could also have done a form post like in here: https://fusionauth.io/docs/v1/tech/oauth/#exchange-the-authorization-code-for-an-access-token

Hope that helps.

Also, you might have better luck posting on the forum, as that typically has more eyes on it: https://fusionauth.io/community/forum/

**Comment by MPH-DZP** [comment]
I don't know if it's the chaining of Promise's, each handling a response, or some special behavior of Express routes that I haven't read about yet...but somehow the request sent by the FA instance in response to `/oath/token` jumps past the code at the beginning of the route-handler to the next Promise. I realize now that this has nothing to do with the FA sample app, so closing this issue.

**Comment by mooreds** [comment]
@MPH-DZP if this is an issue that is confusing to devs new to FusionAuth, definitely want to address it. 

Are you able to get the 5 minute app up and running?

**Comment by MPH-DZP** [comment]
@mooreds I am still mystified about how the requests from the FA instance reach the Promise-resolving callbacks. I'm sure the problem is that my mental model of how Promise's work isn't rich enough to explain how Promise's that are pending inbound network events get triggered. Without that mental model, when I consider just the code in the 5 minute app superficially, there is a mysterious jump/goto from the match of the query path, past the code at the top of the handler, to the resolver callback in the then's. I need to keep an eye out for tutorials about this.

Regarding running the 5 minute app, it works fine locally but when deployed to AWS Beanstalk it fails because the express-session module throws an error about it's being inappropriate to use in a production environment without a `store:` I emailed you separately about whether session storage might use the same connection/service as an app's metadata (e.g. todos)
